name: Bug Report
description: Tell us a bug
labels: "bug"

body:
  - type: checkboxes
    id: checking1
    attributes:
      label: I'm using the latest build release of Muse Dash Mirror and this problem still exsits
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: checking2
    attributes:
      label: There are no similar issues on the issue list
      description: https://github.com/MDModsDev/MuseDashMirror/issues
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: checking3
    attributes:
      label: I've already read the instructions but there's no description telling me about this issue
      description: https://github.com/MDModsDev/MuseDashMirror/blob/master/README.md
      options:
        - label: "Yes"
          required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: which OS you are using ?
      options:
        - Windows 10 and below
        - Windows 11
        - Ubuntu
        - Other Linux distribution
    validations:
      required: true

- type: textarea
    id: version
    attributes:
      label: Game version and Melonloader version
      placeholder: Game version: [e.g. 3.0.0] Melonloader version: [e.g. 0.5.7]
    validations:
      required: true

  - type: textarea
    id: bug_detail
    attributes:
      label: Bug Detail
      placeholder: Please describe your problem in detail
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (Optional)
      placeholder: Clicking on this box and drag your screenshots or videos here to upload. Make sure the screenshots or videos are displayed normally after submitting the issue
    validations:
      required: false

  - type: textarea
    id: download
    attributes:
      label: Logs (Optional)
      placeholder: 1. Go to Muse Dash\MelonLoader; 2. Drag and drop the Latest(.log) here
    validations:
      required: false
