on:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Build Docs
        run: |
          dotnet tool update -g docfx
          docfx ./Documentation/docfx.json
        env:
          WORKER: GitHub

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Documentation/site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4